export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_USERDETAIL_REQUEST = 'GET_USERDETAIL_REQUEST';
export const GET_USERDETAIL_SUCCESS = 'GET_USERDETAIL_SUCCESS';
export const GET_USERDETAIL_FAIL = 'GET_USERDETAIL_FAIL';
